<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>vaudio_openal</RootNamespace>
	</PropertyGroup>

	<!-- Step 1 - copy the OpenAL Soft DLL to the lib folder -->
	<ItemGroup>
		<None Include="lib\soft_oal.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>soft_oal.dll</Link>
		</None>

		<!-- Copy sound files -->
		<None Include="resource\audio\speech.ogg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>resource\audio\speech.ogg</Link>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="vaudio">
			<!-- Step 2 - replace this with the path to your Vercidium Audio .NET SDK -->
			<HintPath>path\to\your\dotnet\vaudio.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="openal_soft_bindings" Version="1.0.8" />
		<PackageReference Include="NVorbis" Version="0.10.5" />
	</ItemGroup>
</Project>
